### ISSUE TITLE
Infinite recursion/loop with `indent-region'

### ISSUE THREAD

**Issue by Alexander-Shukaev** [emacs-evil/evil-surround#113] opened 2017-06-11 23:44 UTC
Let's roll:

```
$ emacs -Q --eval '(add-to-list '"'"'load-path (concat user-emacs-directory "elpa/evil-YYYYMMDD.ABC"))' --eval '(add-to-list '"'"'load-path (concat user-emacs-directory "elpa/evil-surround-YYYYMMDD.ABC"))' --eval '(require '"'"'evil)' --eval '(evil-mode)' --eval '(require '"'"'evil-surround)' --eval '(global-evil-surround-mode)'
```

Move to some word and type `ySiw"`.  Observe infinite hang due to recursion/loop with `indent-region` (see the "Indenting..." message in the minibuffer).  Press `C-g C-g C-g` to break out and observe the correct text modification.

Please, fix.

**Comment by ninrod** [comment] 2017-06-12 01:54
thank you for the bug report. 

Can't reproduce with GNU Emacs 25.2.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.22.10) of 2017-04-22

What is your version?

**Comment by Alexander-Shukaev** [comment] 2017-06-12 06:30
Emacs 26 built yesterday from Git.

**Comment by ninrod** [comment] 2017-12-02 03:54
fixed in GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.26) of 2017-12-02

**Closed by ninrod** 2017-12-02 03:54 UTC
Labels: emacs-26
