### ISSUE TITLE
(global-evil-surround-mode 1) in ~/.emacs not working

### ISSUE THREAD

**Issue by dkrieger** [emacs-evil/evil-surround#107] opened 2017-05-10 16:45 UTC
Placing (global-evil-surround-mode 1) in ~/.emacs doesn't really work. `:help RET v global-evil-surround-mode` shows the desired value (t), but it doesn't actually function unless I run `global-evil-surround-mode` twice (once to "disable", once to enable). I have tried this with the version in melpa, melpa stable, as well as the head from github

Here is my ~/.emacs:

```lisp
;;packages
(setq package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
                         ("org" . "http://orgmode.org/elpa/")
                         ;("marmalade" . "http://marmalade-repo.org/packages/")
                         ("melpa-stable" . "http://melpa-stable.milkbox.net/packages/")
                         ("melpa" . "https://melpa.org/packages/")))
(package-initialize)
;;require
(require 'evil)
(require 'evil-commentary)
(require 'evil-surround)
(require 'undo-tree)
;;intialize
(evil-mode 1)
(evil-commentary-mode 1)
(global-evil-surround-mode 1)
```

here is the Vagrantfile I'm using:

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get -y update
    sudo apt-get -y install emacs vim make git tmux
  SHELL
end
```

**Comment by ninrod** [comment] 2017-05-10 17:06
hi @dkrieger 

`(global-evil-surround-mode 1)` absolutely works for many thousands of users including me. Surely there is something on your configuration. 

try to setup the package from emacs -Q and see if it works. if it works, you need to bisect your config. 

Also, make sure that your emacs version isn't old. `25.1` is recommended.

**Comment by dkrieger** [comment] 2017-05-10 17:37
@ninrod surely 24.* (Whatever is in apt on Debian Jesse after apt-get update) isn't too old? I'll give 25.1 a try

**Comment by dkrieger** [comment] 2017-05-10 20:06
[y|c|d]s registers a "Quit" command if that helps. I'm completely baffled here as the extent of my configuration can be replicated from the above two files

**Comment by ninrod** [comment] 2017-05-10 20:11
try this: 

```elisp
(setq package-archives 
  '(("melpa" . "https://melpa.org/packages/")))

(package-initialize)

;; Bootstrap John Wigley's `use-package'
(unless (package-installed-p 'use-package) 
  (package-refresh-contents)
  (package-install 'use-package))

(use-package evil 
  :ensure t
  :config
  (evil-mode))

(use-package evil-surround
  :ensure t
  :config
  (global-evil-surround-mode 1))
```

**Comment by dkrieger** [comment] 2017-05-10 20:18
thanks @ninrod it works when i do `:e ~/.emacs` and try it on a random word, but if I do `:new RET ihello worldESCysiw` it doesn't work... I feel like we're getting somewhere

**Comment by dkrieger** [comment] 2017-05-10 20:22
setting default mode to text-mode with `(setq-default major-mode 'text-mode)` seems to solve this issue. does surround-mode assume text-mode (or derivative) is active? If so, might be worthwhile to mention that in readme (or I'm just a complete idiot that should have assumed that, but hey, I can't be the only emacs-ignorant vim convert trying to use the plugin). thanks for everything @ninrod

**Comment by ninrod** [comment] 2017-05-10 20:52
@dkrieger, that's interesting. in what mode does emacs leave you in when you type `:new RET ihello worldESCysiw`? 

by the way, you can create new files  using just `M-x find-file`. (C-x C-f)

I've bound this to backspace. find-file also opens files. if the file does not exist, it is created.

**Comment by dkrieger** [comment] 2017-05-10 20:53
@ninrod it drops me in Fundamental mode, presumably matching the open (splash) screen in the absence of a default major mode setting. --no-splash uses Lisp Interaction mode instead, which also avoids this issue

**Comment by ninrod** [comment] 2017-06-01 00:11
hey @dkrieger, can we close this?

**Comment by edkolev** [comment] 2017-06-05 06:55
This issue is caused by a limitation of `define-globalized-minor-mode`. From here (note the second sentence) https://www.gnu.org/software/emacs/manual/html_node/elisp/Defining-Minor-Modes.html

> Globally enabling the mode also affects buffers subsequently created by visiting files, and buffers that use a major mode other than Fundamental mode; but it does not detect the creation of a new buffer in Fundamental mode.

I would suggest the following solution:
Add this in your init.el:
```emacs-lisp
(setq default-major-mode 'text-mode)
```

With the above config, `:new` (and friends) will create new buffers in text mode rather than Fundamental mode

**Closed** 2017-06-07 01:30 UTC
