### ISSUE TITLE
New maintainer for evil-surround!

### ISSUE THREAD

**Issue by ninrod** [emacs-evil/evil-surround#182] opened 2021-12-03 19:42 UTC
Hi @TheBB , @tomdl89 and @wasamasa. I am opening this so we can discuss a new maintainer for evil-surround. 

I am not able anymore to timely maintain the project, respond to issues, etc...

@edkolev , has my vote!

**Comment by tomdl89** [comment] 2021-12-09 20:48
@ninrod sorry to hear you don't have the time any more! @TheBB is somewhat emeritus around here, and I'm not sure about @wasamasa. I don't have a strong objection to @edkolev , but why does he have your vote? I can't see a commit from him on this project in years..? I am happy to turn on notifications for evil-surround and take a look at major bugs, but can't promise much. Hope that's helpful :)

**Comment by wasamasa** [comment] 2021-12-09 23:00
I'm pretty much out, too.

**Comment by ninrod** [comment] 2021-12-15 16:02
@tomdl89 , If I remember correctly,  @edkolev prepared the initial test collections for evil-surround, which was essential in helping with merging contributions.

**Comment by tomdl89** [comment] 2021-12-15 16:05
@ninrod oh sure, I have no doubt he's been instrumental in making evil-surround what it is today. I'm just doubtful he has the desire to maintain evil-surround. Hopefully I'm wrong 🤞

**Comment by jojojames** [comment] 2022-08-18 21:59
Stumbled here after finding evil-surround is erroring out on master/emacs 29.

"⛔ Error (use-package): evil-surround/:catch: Symbol’s value as variable is void: "

How do you all feel merging this into the larger evil-collection project? https://github.com/emacs-evil/evil-ediff, https://github.com/emacs-evil/evil-magit, etc have already been merged successfully and the process went well, I think.

I can do the heavy work of doing the merge if we are happy to deprecate this project in favor of evil-collection.

**Comment by tomdl89** [comment] 2022-08-18 22:16
My understanding is that evil-collection (and those packages that were merged into it) were primarily key-binding packages. Evil surround is not, so I don't think it fits. If I've missed PRs in evil-surround recently I apologise - please feel free to @ me until I respond.

**Comment by jojojames** [comment] 2022-08-18 22:24
> Evil surround is not, so I don't think it fits.

Hmnn, yeah depends on what you think is "keybindings" or not, some of the packages are definitely in the "change key a to key b" but even evil-magit for example, modifies/swaps all the transients instead of just strictly modifying keybinds. I'd consider evil-collection to be receptive to packages that integrate with the vim/vim-esque package experience (e.g. unimpaired). Up to you though, my main goal is just to not have this package go unmaintained/bit rot, so I'd rather sooner rewrite it myself if that means it'll stay up to date.

>  please feel free to @ me until I respond.

The two opens PRs here seem suitable or minor enough IMO but I don't have all the context of course. https://github.com/emacs-evil/evil-surround/pulls

And the issue I came across to even lead me here is not mentioned anywhere so I'm assuming 1. it's specific to my system 2. the subset of users using emacs 29 + evil surround is close to 0? 3. people are adding workarounds without submitting back to this repo.

**Comment by wasamasa** [comment] 2022-08-19 13:24
Few people use Emacs master and few report bugs. I'd expect the likeliness of someone not reporting being higher than someone adding workarounds without contributing them.

That being said, I cannot reproduce your issue. Please open a bug report with a minimal broken example showcasing it.

**Comment by wasamasa** [comment] 2022-08-22 13:17
@jojojames The issue is most likely your use-package invocation being wrong, someone else reported a similar error on r/emacs for a different package: https://old.reddit.com/r/emacs/comments/wun6bd/embarkactall_embarkcatch_symbols_value_as/

**Comment by jojojames** [comment] 2022-08-25 23:09
Not sure, it reproduces on a nightly build from emacsforosx but doesn't when I've built the latest master. Not sure if it's a transient issue...

```
(use-package evil-surround
  :config
  ;; FIXME: Add in Typescript/etc for these surrounds.
  (add-hook 'web-mode-hook
            (lambda ()
              ;; FIXME: Need to check if Typescript..
              (push '(?< . ("< " . " >")) evil-surround-pairs-alist)))
  (add-hook 'c-mode-common-hook
            (lambda ()
              (push '(?< . ("< " . " >")) evil-surround-pairs-alist)))
  (add-hook 'emacs-lisp-mode-hook
            (lambda ()
              (push '(?` . ("`" . "'")) evil-surround-pairs-alist)))
  (global-evil-surround-mode 1))
```

Probably not going to try to chase this down until emacs 29 is nearing closer to release though.

**Comment by tomdl89** [comment] 2023-12-13 13:46
I think I've become the de-facto maintainer, so I'll close this.

**Closed by tomdl89** 2023-12-13 13:46 UTC
Labels: need-help
